name: Test
on:
  workflow_dispatch:

  push:
    branches:
      - '*'
    paths:
      - '**'
      - '!**.md'

  pull_request:
    branches:
      - '*'
    paths:
      - '**'
      - '!**.md'


jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: docker build -t wg . -f Dockerfile
    - name: Test single container
      run:  |
        docker run --rm -id \
        --name cf-warp \
        --sysctl net.ipv6.conf.all.disable_ipv6=0 \
        --privileged --cap-add net_admin \
        -v /lib/modules:/lib/modules \
        -v $(pwd)/cf-warp:/var/lib/cloudflare-warp \
        wg
        while ! docker logs cf-warp | grep "OK, cf-warp is up"; do
          echo wait
          sleep 1
        done
        docker exec -i cf-warp curl ipinfo.io
        docker exec -i cf-warp curl ipv6.ip.sb
        docker run --rm   --network container:cf-warp  curlimages/curl curl ipinfo.io
        docker run --rm   --network container:cf-warp  curlimages/curl curl ipv6.ip.sb
        docker stop cf-warp

    - name: Test single container V4
      run:  |
        docker run --rm -id \
        --name cf-warp \
        --sysctl net.ipv6.conf.all.disable_ipv6=0 \
        --privileged --cap-add net_admin \
        -v /lib/modules:/lib/modules \
        -v $(pwd)/cf-warp:/var/lib/cloudflare-warp \
        wg -4
        while ! docker logs cf-warp | grep "OK, cf-warp is up"; do
          echo wait
          sleep 1
        done
        docker exec -i cf-warp curl ipinfo.io
        docker run --rm   --network container:cf-warp  curlimages/curl curl ipinfo.io
        docker stop cf-warp

    - name: Test single container V6
      run:  |
        docker run --rm -id \
        --name cf-warp \
        --sysctl net.ipv6.conf.all.disable_ipv6=0 \
        --privileged --cap-add net_admin \
        -v /lib/modules:/lib/modules \
        -v $(pwd)/cf-warp:/var/lib/cloudflare-warp \
        wg -6
        while ! docker logs cf-warp | grep "OK, cf-warp is up"; do
          echo wait
          sleep 1
        done
        docker exec -i cf-warp curl ipv6.ip.sb
        docker run --rm   --network container:cf-warp  curlimages/curl curl ipv6.ip.sb
        docker stop cf-warp
        
  Ubuntu-HostMode:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: docker build -t wg . -f Dockerfile
    - name: Test single container
      run:  |
        docker run --rm -id \
        --name cf-warp \
        --net=host \
        --privileged --cap-add net_admin \
        -v /lib/modules:/lib/modules \
        -v $(pwd)/cf-warp:/var/lib/cloudflare-warp \
        wg
        while ! docker logs cf-warp | grep "OK, cf-warp is up"; do
          echo wait
          sleep 1
        done
        curl ipinfo.io
        curl ipv6.ip.sb
        docker stop cf-warp


    - name: Test single container V4
      run:  |
        docker run --rm -id \
        --name cf-warp \
        --net=host \
        --privileged --cap-add net_admin \
        -v /lib/modules:/lib/modules \
        -v $(pwd)/cf-warp:/var/lib/cloudflare-warp \
        wg -4
        while ! docker logs cf-warp | grep "OK, cf-warp is up"; do
          echo wait
          sleep 1
        done
        curl ipinfo.io
        docker stop cf-warp


    - name: Test single container V6
      run:  |
        docker run --rm -id \
        --name cf-warp \
        --net=host \
        --privileged --cap-add net_admin \
        -v /lib/modules:/lib/modules \
        -v $(pwd)/cf-warp:/var/lib/cloudflare-warp \
        wg -6
        while ! docker logs cf-warp | grep "OK, cf-warp is up"; do
          echo wait
          sleep 1
        done
        curl ipv6.ip.sb
        docker stop cf-warp